//
//  CIFliterModel.swift
//  GPUImage3Demo
//
//  Created by 苍蓝猛兽 on 2023/6/21.
//

import UIKit

struct CIFliterModel {
    var fliterName: String?
}

extension CIFliterModel {
    static func systemFilterModels() -> [[String: Any]] {
        return [["filterCategory": "CICategoryBlur", "filters" : [CIFliterModel(fliterName: "CIBoxBlur"),
                                    CIFliterModel(fliterName: "CIDiscBlur"),
                                    CIFliterModel(fliterName: "CIGaussianBlur"),
                                    CIFliterModel(fliterName: "CIMaskedVariableBlur"),
                                    CIFliterModel(fliterName: "CIMedianFilter"),
                                    CIFliterModel(fliterName: "CIMotionBlur"),
                                    CIFliterModel(fliterName: "CINoiseReduction"),
                                    CIFliterModel(fliterName: "CIZoomBlur")]],
                ["filterCategory" : "CICategoryColorAdjustment", "filters": [CIFliterModel(fliterName: "CIColorClamp"),
                                              CIFliterModel(fliterName: "CIColorControls"),
                                              CIFliterModel(fliterName: "CIColorMatrix"),
                                              CIFliterModel(fliterName: "CIColorPolynomial"),
                                              CIFliterModel(fliterName: "CIExposureAdjust"),
                                              CIFliterModel(fliterName: "CIGammaAdjust"),
                                              CIFliterModel(fliterName: "CIHueAdjust"),
                                              CIFliterModel(fliterName: "CILinearToSRGBToneCurve"),
                                              CIFliterModel(fliterName: "CISRGBToneCurveToLinear"),
                                              CIFliterModel(fliterName: "CITemperatureAndTint"),
                                              CIFliterModel(fliterName: "CIToneCurve"),
                                              CIFliterModel(fliterName: "CIVibrance"),
                                              CIFliterModel(fliterName: "CIWhitePointAdjust")]],
                ["filterCategory": "CICategoryColorEffect", "filters": [CIFliterModel(fliterName: "CIColorCrossPolynomial"),
                                          CIFliterModel(fliterName: "CIColorCube"),
                                          CIFliterModel(fliterName: "CIColorCubeWithColorSpace"),
                                          CIFliterModel(fliterName: "CIColorInvert"),
                                          CIFliterModel(fliterName: "CIColorMap"),
                                          CIFliterModel(fliterName: "CIColorMonochrome"),
                                          CIFliterModel(fliterName: "CIColorPosterize"),
                                          CIFliterModel(fliterName: "CIFalseColor"),
                                          CIFliterModel(fliterName: "CIMaskToAlpha"),
                                          CIFliterModel(fliterName: "CIMaximumComponent"),
                                          CIFliterModel(fliterName: "CIMinimumComponent"),
                                          CIFliterModel(fliterName: "CIPhotoEffectChrome"),
                                          CIFliterModel(fliterName: "CIPhotoEffectFade"),
                                          CIFliterModel(fliterName: "CIPhotoEffectInstant"),
                                          CIFliterModel(fliterName: "CIPhotoEffectMono"),
                                          CIFliterModel(fliterName: "CIPhotoEffectNoir"),
                                          CIFliterModel(fliterName: "CIPhotoEffectProcess"),
                                          CIFliterModel(fliterName: "CIPhotoEffectTonal"),
                                          CIFliterModel(fliterName: "CIPhotoEffectTransfer"),
                                          CIFliterModel(fliterName: "CISepiaTone"),
                                          CIFliterModel(fliterName: "CIVignette"),
                                          CIFliterModel(fliterName: "CIVignetteEffect")]],
                ["filterCategory": "CICategoryCompositeOperation", "filters": [CIFliterModel(fliterName: "CIAdditionCompositing"),
                                                 CIFliterModel(fliterName: "CIColorBlendMode"),
                                                 CIFliterModel(fliterName: "CIColorBurnBlendMode"),
                                                 CIFliterModel(fliterName: "CIColorDodgeBlendMode"),
                                                 CIFliterModel(fliterName: "CIDarkenBlendMode"),
                                                 CIFliterModel(fliterName: "CIDifferenceBlendMode"),
                                                 CIFliterModel(fliterName: "CIDivideBlendMode"),
                                                 CIFliterModel(fliterName: "CIExclusionBlendMode"),
                                                 CIFliterModel(fliterName: "CIHardLightBlendMode"),
                                                 CIFliterModel(fliterName: "CIHueBlendMode"),
                                                 CIFliterModel(fliterName: "CILightenBlendMode"),
                                                 CIFliterModel(fliterName: "CILinearBurnBlendMode"),
                                                 CIFliterModel(fliterName: "CILinearDodgeBlendMode"),
                                                 CIFliterModel(fliterName: "CILuminosityBlendMode"),
                                                 CIFliterModel(fliterName: "CIMaximumCompositing"),
                                                 CIFliterModel(fliterName: "CIMinimumCompositing"),
                                                 CIFliterModel(fliterName: "CIMultiplyBlendMode"),
                                                 CIFliterModel(fliterName: "CIMultiplyCompositing"),
                                                 CIFliterModel(fliterName: "CIOverlayBlendMode"),
                                                 CIFliterModel(fliterName: "CIPinLightBlendMode"),
                                                 CIFliterModel(fliterName: "CISaturationBlendMode"),
                                                 CIFliterModel(fliterName: "CIScreenBlendMode"),
                                                 CIFliterModel(fliterName: "CISoftLightBlendMode"),
                                                 CIFliterModel(fliterName: "CISourceAtopCompositing"),
                                                 CIFliterModel(fliterName: "CISourceInCompositing"),
                                                 CIFliterModel(fliterName: "CISourceOutCompositing"),
                                                 CIFliterModel(fliterName: "CISourceOverCompositing"),
                                                 CIFliterModel(fliterName: "CISubtractBlendMode")]],
                ["filterCategory": "CICategoryDistortionEffect", "filters":[CIFliterModel(fliterName: "CIBumpDistortion"),
                                              CIFliterModel(fliterName: "CIBumpDistortionLinear"),
                                              CIFliterModel(fliterName: "CICircleSplashDistortion"),
                                              CIFliterModel(fliterName: "CICircularWrap"),
                                              CIFliterModel(fliterName: "CIDroste"),
                                              CIFliterModel(fliterName: "CIDisplacementDistortion"),
                                              CIFliterModel(fliterName: "CIGlassDistortion"),
                                              CIFliterModel(fliterName: "CIGlassLozenge"),
                                              CIFliterModel(fliterName: "CIHoleDistortion"),
                                              CIFliterModel(fliterName: "CILightTunnel"),
                                              CIFliterModel(fliterName: "CIPinchDistortion"),
                                              CIFliterModel(fliterName: "CIStretchCrop"),
                                              CIFliterModel(fliterName: "CITorusLensDistortion"),
                                              CIFliterModel(fliterName: "CITwirlDistortion"),
                                              CIFliterModel(fliterName: "CIVortexDistortion")]],
                ["filterCategory": "CICategoryGenerator", "filters": [CIFliterModel(fliterName: "CIAztecCodeGenerator"),
                                        CIFliterModel(fliterName: "CICheckerboardGenerator"),
                                        CIFliterModel(fliterName: "CICode128BarcodeGenerator"),
                                        CIFliterModel(fliterName: "CIConstantColorGenerator"),
                                        CIFliterModel(fliterName: "CILenticularHaloGenerator"),
                                        CIFliterModel(fliterName: "CIPDF417BarcodeGenerator"),
                                        CIFliterModel(fliterName: "CIQRCodeGenerator"),
                                        CIFliterModel(fliterName: "CIRandomGenerator"),
                                        CIFliterModel(fliterName: "CIStarShineGenerator"),
                                        CIFliterModel(fliterName: "CIStripesGenerator"),
                                        CIFliterModel(fliterName: "CISunbeamsGenerator")]],
                ["filterCategory": "CICategoryGeometryAdjustment", "filters": [CIFliterModel(fliterName: "CIAffineTransform"),
                                                 CIFliterModel(fliterName: "CICrop"),
                                                 CIFliterModel(fliterName: "CILanczosScaleTransform"),
                                                 CIFliterModel(fliterName: "CIPerspectiveCorrection"),
                                                 CIFliterModel(fliterName: "CIPerspectiveTransform"),
                                                 CIFliterModel(fliterName: "CIPerspectiveTransformWithExtent"),
                                                 CIFliterModel(fliterName: "CIStraightenFilter")]],
                ["filterCategory": "CICategoryGradient", "filters": [CIFliterModel(fliterName: "CIGaussianGradient"),
                                       CIFliterModel(fliterName: "CILinearGradient"),
                                       CIFliterModel(fliterName: "CIRadialGradient"),
                                       CIFliterModel(fliterName: "CISmoothLinearGradient")]],
                ["filterCategory": "CICategoryHalftoneEffect", "filters": [CIFliterModel(fliterName: "CICircularScreen"),
                                             CIFliterModel(fliterName: "CICMYKHalftone"),
                                             CIFliterModel(fliterName: "CIDotScreen"),
                                             CIFliterModel(fliterName: "CIHatchedScreen"),
                                             CIFliterModel(fliterName: "CILineScreen")]],
                ["filterCategory": "CICategoryReduction", "filters":[CIFliterModel(fliterName: "CIAreaAverage"),
                                       CIFliterModel(fliterName: "CIAreaHistogram"),
                                       CIFliterModel(fliterName: "CIRowAverage"),
                                       CIFliterModel(fliterName: "CIColumnAverage"),
                                       CIFliterModel(fliterName: "CIHistogramDisplayFilter"),
                                       CIFliterModel(fliterName: "CIAreaMaximum"),
                                       CIFliterModel(fliterName: "CIAreaMinimum"),
                                       CIFliterModel(fliterName: "CIAreaMaximumAlpha"),
                                       CIFliterModel(fliterName: "CIAreaMinimumAlpha")]],
                ["filterCategory": "CICategorySharpen", "filters": [CIFliterModel(fliterName: "CISharpenLuminance"),
                                      CIFliterModel(fliterName: "CIUnsharpMask")]],
                ["filterCategory": "CICategoryStylize", "filters": [CIFliterModel(fliterName: "CIBlendWithAlphaMask"),
                                      CIFliterModel(fliterName: "CIBlendWithMask"),
                                      CIFliterModel(fliterName: "CIBloom"),
                                      CIFliterModel(fliterName: "CIComicEffect"),
                                      CIFliterModel(fliterName: "CIConvolution3X3"),
                                      CIFliterModel(fliterName: "CIConvolution5X5"),
                                      CIFliterModel(fliterName: "CIConvolution7X7"),
                                      CIFliterModel(fliterName: "CIConvolution9Horizontal"),
                                      CIFliterModel(fliterName: "CIConvolution9Vertical"),
                                      CIFliterModel(fliterName: "CICrystallize"),
                                      CIFliterModel(fliterName: "CIDepthOfField"),
                                      CIFliterModel(fliterName: "CIEdges"),
                                      CIFliterModel(fliterName: "CIEdgeWork"),
                                      CIFliterModel(fliterName: "CIGloom"),
                                      CIFliterModel(fliterName: "CIHeightFieldFromMask"),
                                      CIFliterModel(fliterName: "CIHexagonalPixellate"),
                                      CIFliterModel(fliterName: "CIHighlightShadowAdjust"),
                                      CIFliterModel(fliterName: "CILineOverlay"),
                                      CIFliterModel(fliterName: "CIPixellate"),
                                      CIFliterModel(fliterName: "CIPointillize"),
                                      CIFliterModel(fliterName: "CIShadedMaterial"),
                                      CIFliterModel(fliterName: "CISpotColor"),
                                      CIFliterModel(fliterName: "CISpotLight")]],
                ["filterCategory": "CICategoryTileEffect", "filters": [CIFliterModel(fliterName: "CIAffineClamp"),
                                         CIFliterModel(fliterName: "CIAffineTile"),
                                         CIFliterModel(fliterName: "CIEightfoldReflectedTile"),
                                         CIFliterModel(fliterName: "CIFourfoldReflectedTile"),
                                         CIFliterModel(fliterName: "CIFourfoldRotatedTile"),
                                         CIFliterModel(fliterName: "CIFourfoldTranslatedTile"),
                                         CIFliterModel(fliterName: "CIGlideReflectedTile"),
                                         CIFliterModel(fliterName: "CIKaleidoscope"),
                                         CIFliterModel(fliterName: "CIOpTile"),
                                         CIFliterModel(fliterName: "CIParallelogramTile"),
                                         CIFliterModel(fliterName: "CIPerspectiveTile"),
                                         CIFliterModel(fliterName: "CISixfoldReflectedTile"),
                                         CIFliterModel(fliterName: "CISixfoldRotatedTile"),
                                         CIFliterModel(fliterName: "CITriangleKaleidoscope"),
                                         CIFliterModel(fliterName: "CITriangleTile"),
                                         CIFliterModel(fliterName: "CITwelvefoldReflectedTile")]],
               ["filterCategory": "CICategoryTransition", "filters": [CIFliterModel(fliterName: "CIAccordionFoldTransition"),
                                         CIFliterModel(fliterName: "CIBarsSwipeTransition"),
                                         CIFliterModel(fliterName: "CICopyMachineTransition"),
                                         CIFliterModel(fliterName: "CIDisintegrateWithMaskTransition"),
                                         CIFliterModel(fliterName: "CIDissolveTransition"),
                                         CIFliterModel(fliterName: "CIFlashTransition"),
                                         CIFliterModel(fliterName: "CIModTransition"),
                                         CIFliterModel(fliterName: "CIPageCurlTransition"),
                                         CIFliterModel(fliterName: "CIPageCurlWithShadowTransition"),
                                         CIFliterModel(fliterName: "CIRippleTransition"),
                                         CIFliterModel(fliterName: "CISwipeTransition")]]]
    }
}
